### ISSUE TITLE
Document Sync-Endpoint is compatible with what DB version

### ISSUE THREAD

**Issue by wbrunette** [odk-x/tool-suite-X#104]
Document the minimum and tested version of MySql and Posgres so users know which databases to use.

**Comment by vmaldosan** [comment]
Just wanted to add that MS SQL Server is also mentioned in the document, so it may be a good idea to add its supported version as well :)

**Comment by CtripleU** [comment]
Hello, @wbrunette. 
While working on issue #180, I came across the minimum tested/recommended versions for MySQL and PostgreSQL in the readme file for the Sync-Endpoint. I'd like to resolve this issue by adding them to the documentation. Could you please assign this to me? Thank you.

**Comment by wbrunette** [comment]
@CtripleU I am assigning this to you. Instead of having the versions in two places that require updates, it makes more sense to add a link to the documentation that points to the README file to get the versions.

**Comment by CtripleU** [comment]
Noted, @wbrunette. Thank you

**Comment by CtripleU** [comment]
Hello, @wbrunette. I just opened a PR to fix this. Kindly review. Thanks!
