### ISSUE TITLE
Document text formatting options for survey

### ISSUE THREAD

**Issue by elmps2018** [odk-x/tool-suite-X#105]
Document the options for formatting (bold, italics, etc.) how text displays in survey. Which columns can be formatted and what are the formatting options?

**Comment by shivanisinghnitp** [comment]
Hello I am an outreachy applicant. Can this issue be assigned to me?

**Comment by linl33** [comment]
Hi @shivanisinghnitp,

I've assigned this issue to you. Thanks for participating in Outreachy. Let us know if you have any questions.

You could start from https://docs.odk-x.org/survey-sample-app/ to get an idea of ODK-X Survey then follow https://docs.odk-x.org/getting-started-2-architect/ to learn to build a form.

**Comment by shivanisinghnitp** [comment]
Thank you so much ! I have started working on it! @linl33

**Comment by wbrunette** [comment]
@shivanisinghnitp can you give us an update on this issue? do you have any questions? If you no longer want to work on this issue please let us know.

**Comment by shivanisinghnitp** [comment]
I am sorry but because of some issues in my family I could not complete the issue! 
You can unassign me.
Thank you!

**Comment by elmps2018** [comment]
@shivanisinghnitp thanks for letting us know!

**Comment by iamhks** [comment]
Hi all, can I work on this?

**Comment by elmps2018** [comment]
Hi @iamhks it looks(?) like you have at least two open issues, we tend to ask people to work on a couple at a time until they finish (although I see you have work going right now!) so once those are finished if you want to come back to this and it's still available we can assign you.

**Comment by iamhks** [comment]
@elmps2018 I am aware of this and I wouldn't have asked if that was the case.
![Screenshot from 2021-04-27 03-00-38](https://user-images.githubusercontent.com/43777817/116153415-e34b4200-a704-11eb-9a54-17bdba73ebd8.png)
I have already made a PR for both first (which in itself is an ongoing one) and second issue so I only have 1 active issue assigned to me.

**Comment by elmps2018** [comment]
@iamhks Ah-ha, got confused by the first one! Assigned you now.

**Comment by iamhks** [comment]
Hi @elmps2018 I am a little confused with this. I was unable to find the formatting options in doc & the app. So I checked out the app designer but still there were just text color and font type and nothing in terms of how text displays in survey. Can you help me out?

![Screenshot from 2021-04-28 14-14-20](https://user-images.githubusercontent.com/43777817/116375177-a67a6a80-a82c-11eb-839a-b4a6bcdfa179.png)
![Screenshot from 2021-04-28 14-16-01](https://user-images.githubusercontent.com/43777817/116375201-abd7b500-a82c-11eb-8829-55f231508450.png)

**Comment by elmps2018** [comment]
Hi @iamhks sorry for the confusion! These would be modifications you can make in your xlsx file for a survey. For example, you can bold, italicize, etc. anything that is in the display.prompt.text column. So this is not in the chrome interface so much as the excel file. Folks don't know that/what options are available for customization.
