### ISSUE TITLE
Rename Injected JavaScript Interfaces

### ISSUE THREAD

**Issue by elmps2018** [odk-x/tool-suite-X#117]
Injected JavaScript Interfaces is a confusing name to the less-technical audience. Suggest one of the following:
Customizing interfaces
Customizing user interfaces
Interface customization

**Comment by linl33** [comment]
@elmps2018 You renamed it to **ODK-X WebKit** in https://github.com/odk-x/docs/pull/29, can we close this issue?

**Comment by elmps2018** [comment]
So I did! Yes, let's close this, WebKit at least is somewhat more accessible.
