### ISSUE TITLE
Document barcode scanner intent for Tables

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#119]
The `com.google.zxing.client.android.SCAN` intent to launch a barcode scanner should be documented with its `odkCommon.doAction` parameters and the expected callback contents.

**Comment by shaliniiit** [comment]
Hi I'd like to work on this issue. Is commenting enough to claim it?

**Comment by wbrunette** [comment]
@shaliniiit I have assigned this issue to you.

**Comment by shaliniiit** [comment]
Thank you.

**Comment by sheykerkup** [comment]
@wbrunette I will like to work on this issue.

**Comment by wbrunette** [comment]
@sheykerkup  I have assigned this issue to you.

**Comment by sheykerkup** [comment]
Where can I currently find this feature? Can I have a little more details as to which ODK-X tools this belongs to and how to replicate the new feature on my android device?

**Comment by sheykerkup** [comment]
> @sheykerkup I have assigned this issue to you.

Ok

**Comment by wbrunette** [comment]
> Where can I currently find this feature? Can I have a little more details as to which ODK-X tools this belongs to and how to replicate the new feature on my android device?

You can launch from ODK-X Tables webkit by using the ODK-X java interface available in odkCommon
odkCommon.doAction(dispatchStruct, 'com.google.zxing.client.android.SCAN', null);

See documentation:
https://docs.odk-x.org/injected-interfaces/#doaction

**Comment by sheykerkup** [comment]
> > Where can I currently find this feature? Can I have a little more details as to which ODK-X tools this belongs to and how to replicate the new feature on my android device?
> 
> You can launch from ODK-X Tables webkit by using the ODK-X java interface available in odkCommon odkCommon.doAction(dispatchStruct, 'com.google.zxing.client.android.SCAN', null);
> 
> See documentation: https://docs.odk-x.org/injected-interfaces/#doaction

Thank you very much. I will take on this immediately.

**Comment by sheykerkup** [comment]
Hi @wbrunette, I succeeded to launch a barcode scanner and processed a barcode successfully. I also noticed to do this I had to install a barcode scanner having the package `com.google.zxing.client.android.SCAN` on my device before it could work. 

I have sent a sample of where I would like to place this documentation in the PR. Please confirm if that is ok or needs some changes.

**Comment by sheykerkup** [comment]
> Hi @wbrunette, I succeeded to launch a barcode scanner and processed a barcode successfully. I also noticed to do this I had to install a barcode scanner having the package `com.google.zxing.client.android.SCAN` on my device before it could work.
> 
> I have sent a sample of where I would like to place this documentation in the PR. Please confirm if that is ok or needs some changes.

@elmps2018  this was the comment I left earlier.

**Comment by wbrunette** [comment]
for clarification - @elmps2018 and @EstherPhebe, @sheykerkup has a picture of where he would like to put the barcode scanner documentation in the first comment here: https://github.com/odk-x/docs/pull/161

**Comment by elmps2018** [comment]
Ah-ha, okay, tracking this better now :) So it seems like the suggested page is just full of lists up until there. Should this just be a list item? Or do we want a worked-through example (or this needs more detail than the other listed items) to help people?

**Comment by sheykerkup** [comment]
> Ah-ha, okay, tracking this better now :) So it seems like the suggested page is just full of lists up until there. Should this just be a list item? Or do we want a worked-through example (or this needs more detail than the other listed items) to help people?

Yes, you put it a bit clearer. That is what I meant to ask? I was thinking that page is already full but wonder where else I could put the information. Is there any other section this could fit better or do I need to create a whole different section (if yes what heading)

**Comment by sheykerkup** [comment]
@wbrunette  @elmps2018  I have linked the complete documentation for this process with sample code I used to achieve this. Please checkit out. For some reason, I can not seem to tag you all on that repository. https://github.com/odk-x/docs/pull/183

**Comment by permission-error1** [comment]
@sheykerkup u can always tag them manually

**Comment by sheykerkup** [comment]
> @sheykerkup u can always tag them manually

Thanks. I will try that now.
