### ISSUE TITLE
Suitcase should save credentials

### ISSUE THREAD

**Issue by jbeorse** [odk-x/tool-suite-X#133]
Suitcase requires credentials to be added every time. 

The tradeoff is that this creates files on the user's computer.

From the 2019 convening: https://docs.google.com/document/d/1_4x9x3eHxo4qevBRlpmCC9L2bVlUkAQuAlidT8wJDzI/edit#

**Comment by Shubhamr837** [comment]
Hi , I would like to work on this issue . 
Should we store the login credentials in an encrypted format in a file to login the user after he exists the application?

**Comment by ADISKING1** [comment]
I gave this issue some thought earlier today. It appears that there are multiple ways to approach this. One approach that I had in mind was to make use of the **Java Properties** API but this method is not as secure as the other available options. I would like to hear the thoughts of our mentors and other fellow developers on the same.

**Comment by wbrunette** [comment]
@Shubhamr837 if you are doing GSoC you may want to make this part of your proposal for https://forum.odk-x.org/t/internship-project-improve-the-odk-x-suitcase-application/1190

**Comment by Shubhamr837** [comment]
Thanks a lot  , I would try to do it in the best way possible.
