### ISSUE TITLE
Document Sync Client

### ISSUE THREAD

**Issue by jbeorse** [odk-x/tool-suite-X#142]
Sync client is an important library for implementing and understanding the sync protocol but you basically need to already know it exists. It should be documented. 

From the 2019 convening: https://docs.google.com/document/d/1_4x9x3eHxo4qevBRlpmCC9L2bVlUkAQuAlidT8wJDzI/edit#heading=h.264josm5lg7

**Comment by elmps2018** [comment]
I couldn't find any documentation yet on this one.

**Comment by iamhks** [comment]
Hi all, I would like to work on this!

**Comment by elmps2018** [comment]
@iamhks assigned you!

**Comment by iamhks** [comment]
@elmps2018 Could you elaborate this a little? I see this: https://docs.odk-x.org/sync-endpoint/
I understand that we need to document Sync client library, some resource where I can learn about the same would be helpful.

**Comment by elmps2018** [comment]
@iamhks this is a tricky one because it does not yet have documentation, you may need to look at the code -- @linl33 or @wbrunette can you point to where?

**Comment by linl33** [comment]
@iamhks For now I think it will be enough to document that the sync-client library exists, where it is, and a description of its purpose. The source is at https://github.com/odk-x/sync-client.
