### ISSUE TITLE
Improve documentation of LDAP setup

### ISSUE THREAD

**Issue by jbeorse** [odk-x/tool-suite-X#145]
Write something about how to set up; also possibly example server would circumvent; Better LDAP

From the 2019 convening: https://docs.google.com/document/d/1_4x9x3eHxo4qevBRlpmCC9L2bVlUkAQuAlidT8wJDzI/edit#heading=h.264josm5lg7

**Comment by elmps2018** [comment]
I think we have done this? See https://docs.odk-x.org/getting-started-2-architect/?highlight=wipe#useful-grunt-commands

**Comment by wbrunette** [comment]
LDAP is part of the sync-endpoint-default-setup. There is a page on LDAP but it does not go into much detail.

**Comment by wbrunette** [comment]
See: https://docs.odk-x.org/sync-endpoint/#ldap

**Comment by Shubhamr837** [comment]
Hi @elmps2018  , can I work on this ?

**Comment by elmps2018** [comment]
@Shubhamr837 sure! Just assigned it to you.

**Comment by Shubhamr837** [comment]
Thanks , I wanted some more details about this . 
In the existing documentation at https://docs.odk-x.org/sync-endpoint/#ldap , there are instructions about how to set up using 
phpLDAPadmin server but no instructions about how to configure using OpenLDAP command line utilities . Should i include that ?

**Comment by elmps2018** [comment]
@jbeorse or @wbrunette could you expand on what improvements are needed in LDAP documentation?

**Comment by wbrunette** [comment]
This documentation should be added as an advanced/customization section.

There is some additional information in the readme that should be organized and added to the documentation: https://github.com/odk-x/sync-endpoint-default-setup

- [ ] Document how to configure the defaults of OpenLDAP ([example environment variables file](https://github.com/odk-x/sync-endpoint-default-setup/blob/master/ldap.env))
- [ ] Document how to use another LDAP UI (other than phpldapadmin) to access the OpenLDAP.
- [ ] Document how to change Sync-Endpoint to use/access a different LDAP than the OpenLDAP in the Docker swarm

**Comment by Shubhamr837** [comment]
@wbrunette Thanks , I get it now.
