### ISSUE TITLE
Improve determination of compatible API version

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#150]
Sync Endpoint API requires the client to provide an API version, known internally as `odkClientVersion` or `odkClientApiVersion`, currently the only valid version is 2. Its usage is documented on the [Sync Protocol page](https://docs.opendatakit.org/odk-x/odk-2-sync-protocol/).

ODK-X Services determines the API version by truncating off the last 2 digits of the release rev version, e.g. version 2.1.5 rev236 ⇒ 2. Services could use a more robust method to determine the API version for example storing the version in a constants file.

Relevant code in ODK-X Services:
https://github.com/opendatakit/services/blob/670be84a409c763ba21a104487542e52c740aebf/services_app/src/main/java/org/opendatakit/services/sync/service/SyncExecutionContext.java#L100

**Comment by IAmJaishree** [comment]
@linl33  Can I take this as my first issue?

**Comment by linl33** [comment]
Hi @IAmJaishree,
Yes, please go ahead. Thanks.

**Comment by wbrunette** [comment]
Closed by: odk-x/services#182
