### ISSUE TITLE
Document prompt textarea

### ISSUE THREAD

**Issue by wbrunette** [odk-x/tool-suite-X#152]
Document the prompt text area.

**Comment by ChitvanRamani22** [comment]
@elmps2018 could you please assign this to me.

**Comment by elmps2018** [comment]
Hi @ChitvanRamani22! We request new contributors to work on one issue at I time, I saw you asking about #143  as well, please let us know which you would prefer to do. Once you finish one issue, if the other is still available you can do it next.

**Comment by ChitvanRamani22** [comment]
@elmps2018 as this will be my first issue for outreachy whichever you feel is a better one to start you can assign me that.

**Comment by wbrunette** [comment]
@ChitvanRamani22 this issue is probably a better one to start with. I would recommend going through the getting started and understanding how to make a form. Then you can try out the prompt textarea that is missing from the documentation.

**Comment by ChitvanRamani22** [comment]
@elmps2018 thanks for assigning. Will reach you out in case of any doubt.

**Comment by ChitvanRamani22** [comment]
@wbrunette @elmps2018 can you please help me in setting up the repo in my local machine

**Comment by wbrunette** [comment]
@ChitvanRamani22 which repo are you referring to?

**Comment by emmyclef** [comment]
could you pls assign this to me as well

**Comment by khushishikhu** [comment]
@wbrunette if no one is working here can I start working on it?

**Comment by wbrunette** [comment]
@ChitvanRamani22 can you give us an update on your progress? Do you have questions we could answer? If you are not longer working on it please let us know so we can assign this to someone else.

**Comment by ChitvanRamani22** [comment]
@wbrunette due to some family issues i could not continue to work on this you can assign this to someone else.
Sorry for the late response.

**Comment by wbrunette** [comment]
@ChitvanRamani22 I am sorry to hear about your family issues. I hope everything ends up well. Thanks for letting us know.
@khushishikhu I have assigned the issue to you.

**Comment by ChitvanRamani22** [comment]
@wbrunette thanks a lot for your patience.

**Comment by khushishikhu** [comment]
![Capture](https://user-images.githubusercontent.com/65439761/114292739-52425d00-9aae-11eb-8456-88d053c94d52.PNG)
@wbrunette This is the code for prompt textarea, can you please help me to know if I have to write the document for prompt textarea in Survey, Table, or services? or somewhere else?

**Comment by wbrunette** [comment]
@khushishikhu please add it to the list of available prompt types. Also please add a note about string size. https://forum.odk-x.org/t/odk-x-character-limits/532/ since the text area are likely to have people go over 255 characters.
