### ISSUE TITLE
Show last synced time and date in ODK-X Services

### ISSUE THREAD

**Issue by elmps2018** [odk-x/tool-suite-X#155]
There doesn't seem to be any way to tell, in ODK services, when I last synced. This would be a very helpful item to display on the syncing screen so that if, say, you are an enumerator and the field supervisor emails to say "I added new observations at 9am yesterday, please make sure you have synced" you can just pop open the syncing screen and see whether or not you've synced since 9am yesterday. Supervisors could also pop open fieldworkers tablets to make sure everything has synced at the end of day. I am guessing this info already exists somewhere inside Services, so hopefully this would be easy to display!

**Comment by pawanharariya** [comment]
I tried studying code base for a while and I didn't see any information about last sync info. I am thinking to save current system time in shared preferences once sync in completed and display it. If this is a right approach I will implement it and send a PR, if not any guidance will be helpful.

**Comment by wbrunette** [comment]
@pawanharariya your proposed solution sounds like a good approach. Go ahead and implement a PR for review.

**Comment by pawanharariya** [comment]
> @pawanharariya your proposed solution sounds like a good approach. Go ahead and implement a PR for review.

I sent a PR https://github.com/odk-x/services/pull/181. Please review.
