### ISSUE TITLE
XLSX converter doesn't trim whitespace from column names

### ISSUE THREAD

**Issue by albertchae** [odk-x/tool-suite-X#157]
example `calculation_name ` on the `calculates` tab will result in an error

**Comment by linl33** [comment]
https://github.com/odk-x/app-designer/blob/9e06f420276a2c08f7e8ca5091b65aa3bc38ee0c/xlsxconverter/XLSXConverter2.js#L581-L587

```js
        _.each(row, function(value, key){
            if(_.isString(value)){
                value = value.replace(/\r/g, "");
                value = value.trim();
            }
            outRow[key] = value;
        });
```

Calling `trim` on `key` should fix this issue.

**Comment by EstherPhebe** [comment]
@linl33  I'd like to work on this. From what I see the trim method should be called on the key parameter to remove the trailing whitespace. Will the key argument always be a string?

**Comment by linl33** [comment]
@EstherPhebe I've assigned this issue to you. Be sure to test thoroughly that fixing this issue doesn't break existing forms. Thanks!

`key` should always be a string given that it was used to index `outRow`.
