### ISSUE TITLE
Synchronization options

### ISSUE THREAD

**Issue by antenehtassalif** [odk-x/tool-suite-X#162]
Synchronization has 4 options. I tried the “Upload Only” one and it doesn’t work as promised; I ended up downloading the content of the server. I haven't checked other options, but this is also sort of an essential issue.

**Comment by elmps2018** [comment]
Can you tell us more about this issue? Is this in ODK-X services that you are choosing options for synchronization? Synchronization will generally download the contents of the server (and upload too).

**Comment by antenehtassalif** [comment]
Thanks, @elmps2018. This was a misunderstanding.
