### ISSUE TITLE
ensure app-designer setup is documented

### ISSUE THREAD

**Issue by wbrunette** [odk-x/tool-suite-X#172]
There are two sets of instructions for app designer, one from the zip download and one for someone doing a fresh checkout. Make sure both are documented. 

Especially the README should document for developers.

**Comment by adityaofficial10** [comment]
@wbrunette 
Can I move ahead with the documentation part?
I am already familiar with most of ODK tools.😅

**Comment by wbrunette** [comment]
@adityaofficial10 you can move ahead. Please make sure to document both paths as a checkout requires an npm install. When we post the full zip for release we include the packages.

**Comment by adityaofficial10** [comment]
@wbrunette 
Sure, I'll take care of that..

**Comment by linl33** [comment]
@adityaofficial10 Could you give us an update on this issue? Let us know if you have any questions or would like to be unassigned.

**Comment by adityaofficial10** [comment]
@linl33 
I think I won't be able to complete this due to health issues.
Thanks for persisting..

**Comment by linl33** [comment]
@adityaofficial10 I hope you get well soon.

**Comment by adityaofficial10** [comment]
@linl33 
Thanks a lot.

**Comment by iamhks** [comment]
Hi @linl33 I would like to work on this issue. Please tell me if I understand this issue; the installation steps of https://docs.odk-x.org/app-designer-install/ needs to be documented into https://github.com/odk-x/app-designer 's readme right? Also where can I find the reference to the one for someone doing a fresh checkout?

**Comment by wbrunette** [comment]
@iamhks I am assigning the issue, the instructions are in the docs. https://docs.odk-x.org/app-designer-setup/

**Comment by iamhks** [comment]
@wbrunette I have made a PR, please review. Thanks
