### ISSUE TITLE
Add 'signature' type to prompt type list

### ISSUE THREAD

**Issue by wbrunette** [odk-x/tool-suite-X#174]
1) The prompt type signature appears to be missing from the list
https://docs.odk-x.org/xlsx-converter-reference/#id4

2) The url could probably be improved to 'survey-prompt-types' instead of 'id4'

**Comment by deepak-prajapatii** [comment]
@wbrunette Can I work on this issue?

**Comment by wbrunette** [comment]
@deepak-prajapatii I have assigned the issue to you.

**Comment by deepak-prajapatii** [comment]
> @deepak-prajapatii I have assigned the issue to you.

Thanks, Now  I am working on this issue.

**Comment by deepak-prajapatii** [comment]
@wbrunette Hey, where I need to add the "signature" type?

**Comment by deepak-prajapatii** [comment]
@wbrunette Hey, Can I get some more details about where and how can I add signature type?

**Comment by wbrunette** [comment]
The signature type exists, it is simply not document. Create a XLSX definition for Survey and use type signature. Then update the documentation to help users use it. Documentation being our docs.odk-x.org website. To make updates to the website you change the https://github.com/odk-x/docs repo.

**Comment by deepak-prajapatii** [comment]
> The signature type exists, it is simply not document. Create a XLSX definition for Survey and use type signature. Then update the documentation to help users use it. When we say update the documentation we mean to update our docs.odk-x.org website. To make updates to the website you change the https://github.com/odk-x/docs repo.

Okay, I am trying to solve it.

**Comment by EstherPhebe** [comment]
@wbrunette @elmps2018 Hello, I would like to work on this issue. Can you please assign it to me?

**Comment by wbrunette** [comment]
@EstherPhebe I have assigned the issue to you. Thanks for improving our documentation.

**Comment by EstherPhebe** [comment]
@wbrunette Seen, currently working on it. If I run into any issues that I cannot solve myself, I'll let you know.
