### ISSUE TITLE
Add more precision to make Enpoint running over HTTPS

### ISSUE THREAD

**Issue by yanokwa** [odk-x/tool-suite-X#178]
Originally filed at https://github.com/getodk/docs/issues/1180.

> An instruction is missing to help people to make ODK EndPoint running over HTTPS.
> 
> On the https://docs.opendatakit.org/odk-x/sync-endpoint page, in the HTTPS paragraph I would add that one must edit the docker-compose.yml file and change the value of file : com.nginx.sync-endpoint.conf to ./config/nginx/sync-endpoint-https.conf

**Comment by wbrunette** [comment]
Fixed odk-x/docs#10
