### ISSUE TITLE
Survey table of contents has hard-coded heading

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#185]
The table of contents has a hard-coded heading `Contents`.

The heading should use a translation key to allow internationalization. `options_popup_contents_heading` in `framework_translations` could be used for this. Or a new key should be added to `framework_translations`.

https://github.com/odk-x/app-designer/blob/7abf14b16d940850cedfa66e2f9c2afd79553b3e/app/system/survey/templates/contents.handlebars#L1

**Version**
2.1.7

**Comment by adityaofficial10** [comment]
@linl33 
I am working on a similar issue.
Can I merge this commit with it?

**Comment by linl33** [comment]
If you're referring to https://github.com/odk-x/survey/pull/143, these 2 issues do not belong to the same repository

**Comment by starboi02** [comment]
@linl33 can I work on this one?

**Comment by linl33** [comment]
@adityaofficial10, have you started to work on this? If not, please let @starboi02 take on this issue.

**Comment by adityaofficial10** [comment]
@linl33 
I've started but yeah I have no problems if he works on it.✌

**Comment by wbrunette** [comment]
Thanks @adityaofficial10.

@starboi02 I have assigned the issue to you, so feel free to start working on it.

Are you thinking of participating in Google Summer of Code? Here is a link to our main forum post that should help you get started: https://forum.odk-x.org/t/welcome-gsoc-applicants/1195

**Comment by starboi02** [comment]
> Thanks @adityaofficial10.
> 
> @starboi02 I have assigned the issue to you, so feel free to start working on it.
> 
> Are you thinking of participating in Google Summer of Code? Here is a link to our main forum post that should help you get started: https://forum.odk-x.org/t/welcome-gsoc-applicants/1195

@wbrunette Yes I am thinking of participating in GSOC. Thanks for the guidance!

**Comment by linl33** [comment]
Fixed by odk-x/app-designer#185
