### ISSUE TITLE
Add a Grunt command to pull ODK-X logs

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#186]
A Grunt command similar to `adbpull-db` and `adbpull-csv` but for the logs stored at `output/logging` would be very useful for debugging.

This new command can follow the implementation for `adbpull-csv` (linked below)
https://github.com/odk-x/app-designer/blob/7abf14b16d940850cedfa66e2f9c2afd79553b3e/Gruntfile.js#L316-L325

**Version**
2.1.7

**Comment by adityaofficial10** [comment]
@linl33 
I've gone through the implementation of adbpull-csv.
Can I work on this issue?

**Comment by linl33** [comment]
Please send a pull request to [odk-x/app-designer](https://github.com/odk-x/app-designer) against **development** branch. Thanks.

**Comment by wbrunette** [comment]
Closed by: https://github.com/odk-x/app-designer/pull/148
