### ISSUE TITLE
Sync-Endpoint UI Fix - Replace Row eTag with row ID 

### ISSUE THREAD

**Issue by wbrunette** [odk-x/tool-suite-X#188]
Currently the Sync-Endpoint displays the "Row eTag" as the first column when displaying rows. It should instead display the row ID (in the table _id).

**Comment by adityaofficial10** [comment]
@wbrunette 
Can I move forward with this?

**Comment by wbrunette** [comment]
@adityaofficial10 Yes. Thanks for claiming the issue.

**Comment by IAmJaishree** [comment]
@adityaofficial10 Is it possible for me to take this issue if you have not started with it yet?

**Comment by linl33** [comment]
@adityaofficial10 Could you give us an update on this issue? Let us know if you have any questions or would like to be unassigned.

**Comment by adityaofficial10** [comment]
@linl33 
I think I won't be able to complete this due to health issues.
Thanks for persisting..

**Comment by linl33** [comment]
@adityaofficial10 I hope you get well soon.

**Comment by adityaofficial10** [comment]
@linl33 
Thanks a lot.

**Comment by wbrunette** [comment]
@RyanLi0802 I will assign it to you

**Comment by RyanLi1028** [comment]
sure
