### ISSUE TITLE
Document showFooter/showHeader option for forms

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#189]
`showFooter` and `showHeader` options for Survey forms are not documented.

**Comment by adityaofficial10** [comment]
@linl33 
I can work with the documentation if you allow.

**Comment by Chi-O** [comment]
@linl33 hello, I am just getting started in open-source development and I would love to contribute in any way I can if this issue is still available

**Comment by linl33** [comment]
Hi @Chi-O. Yes this is still available and I've assigned this issue to you. If you're considering participating in Outreachy please see https://forum.odk-x.org/t/welcome-outreachy-applicants/1240. If you're considering participating in GSoC please see https://forum.odk-x.org/t/welcome-gsoc-applicants/1195.

**Comment by Chi-O** [comment]
thank you! yes, I am an aspiring GSoC applicant and looking to work on an issue as advised :) 
could you kindly guide me on how to proceed with adding these options to the Survey documentation? I want to confirm which section this belongs

**Comment by linl33** [comment]
These 2 options should go on the XLSX Reference page https://docs.odk-x.org/xlsx-converter-reference/#settings 

You can find information on how to modify the documentation at https://github.com/odk-x/docs#odk-x-docs

**Comment by khushishikhu** [comment]
@linl33 If no one is working on this issue. Can I start working on this issue?

**Comment by wbrunette** [comment]
@Chi-O can you give us an update on your progress? Do you have questions we could answer? If you are not longer working on it please let us know so we can assign this to someone else.

**Comment by Chi-O** [comment]
I apologize for not getting this done sooner, I got busy with my other projects. I followed the instructions on the docs contribution guide and I have set up the repository on my end. I want to make sure to follow the guidelines for markup, syntax and style so that is what I am going through now.

**Comment by Chi-O** [comment]
@linl33 @wbrunette would these options be part of the available [setting_name values](https://docs.odk-x.org/xlsx-converter-reference/#setting-name-value) shown? kindly help me in describing the settings

**Comment by linl33** [comment]
@Chi-O Yes, `showFooter` and `showHeader` should be added to that table. You can try them out in a form to see what they do.
