### ISSUE TITLE
Hard-coded text in Survey's sort.xml

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#190]
https://github.com/odk-x/survey/blob/1e2908b4433d7004d71cba4c2724aa43a2c9bfcd/survey_app/src/main/res/menu/sort.xml#L4

This should be replaced by a string resource.

**Comment by adityaofficial10** [comment]
@linl33 
I've made the changes.
<img width="469" alt="Screenshot 2021-03-06 at 10 01 36 PM" src="https://user-images.githubusercontent.com/65034276/110213804-99de3380-7ec7-11eb-9906-1087b8f3031b.png">
Kindly review this.

**Comment by linl33** [comment]
Please send a pull request to [odk-x/survey](https://github.com/odk-x/survey) against **development** branch.

**Comment by starboi02** [comment]
@linl33 can I work on it?

**Comment by riturajjain2000** [comment]
Can I look into this ?

**Comment by wbrunette** [comment]
@starboi02 I have assigned this issue to you.
