### ISSUE TITLE
Update DigitalOcean setup script with new size slugs

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#195]
Reported on forum: https://forum.odk-x.org/t/update-size-slug-for-python-script/1163

The line on https://github.com/odk-x/docs/blob/6c8268cabfa53f8fec3671c789067fbaa237fb30/odkx-src/files/pyscript_DO.py#L21 needs to be updated to one of the new slugs listed on https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/

**Comment by adityaofficial10** [comment]
Hey @linl33 !
Would 4GB version, i.e. 's-2vcpu-4gb' be fine?

**Comment by linl33** [comment]
Hi @adityaofficial10, 
You will need a DigitalOcean account to test the changes. Please confirm you have an account.

**Comment by adityaofficial10** [comment]
@linl33 I have the account.

**Comment by wbrunette** [comment]
eliminated the script and now use Digitial ocean console based instructions
