### ISSUE TITLE
Tables/Survey crash with HTML select on Android 5.1

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#196]
Reported on forum, https://forum.odk-x.org/t/html-dropdown-does-not-show/1175

Tables and Survey crash when an HTML select is clicked.
Tested on Android Emulator version 5.1 Google API.

**Comment by wbrunette** [comment]
Was the WebView upgraded via Google Play? As updated libraries depend on upgraded WebViews.

**Comment by linl33** [comment]
Only tested with the stock version. I will try with an updated webview.

**Comment by starboi02** [comment]
Can I work on it?

**Comment by wbrunette** [comment]
@starboi02 a fix for this issue is being tested. I suggest tackling another issue.
