### ISSUE TITLE
Default Suitcase CLI's dataVersion to 2

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#197]
`dataVersion` is a required argument in Suitcase's CLI. In practice, the value for this argument is always 2. Suitcase could provide a default value for this argument to simplify usage.

**Comment by avinash14022002** [comment]
@linl33  sir,
wanted to work on the issue please let me know how to start with..!!!

**Comment by linl33** [comment]
Hi @avinash14022002! Please see the **getting started** section on https://forum.odk-x.org/t/welcome-gsoc-applicants/1195 and the README on https://github.com/odk-x/suitcase
