### ISSUE TITLE
Add description on app-designer's QR code generator

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#198]
App-designer's QR code generator generates a QR code for ODK-X Services to log in to a Sync Endpoint server. The code generator could provide a description on the page of what it does and how to use it.

**Comment by sayant1204** [comment]
Hi @linl33,
Can I work on this issue?

**Comment by linl33** [comment]
Hi @sayant1204,
Yes, please go ahead. Thank you.

**Comment by linl33** [comment]
@sayant1204 Could you give us an update on this issue? Let us know if you have any questions.

**Comment by sanyud24** [comment]
Hi , I'm sanyu daver an outreachy applicant   , May I work on this issue @linl33

**Comment by wbrunette** [comment]
@sanyud24 I have assigned this issue to you to work on.

@sayant1204 if you almost done, let us know and post as pull request and I will reassign it back to you. However we haven't heard from you in 28 days so I am going to assume that you moved on to something else. If I am wrong let me know.

**Comment by sanyud24** [comment]
I'm really sorry to trouble you but I've been searching for some  good first issue on ODK - X suitcase app .  . I read this issue incorrectly ,please unassign this, May u suggest some open issues on the suitcase app ? It'll be very helpful , Thankyou

**Comment by EstherPhebe** [comment]
@linl33 Can I work on this?

**Comment by linl33** [comment]
@EstherPhebe I've assigned this issue to you.
