### ISSUE TITLE
Document login with QR code

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#199]
ODK-X Services supports scanning a QR code to login to a server. This feature should be documented.

**Comment by IAmJaishree** [comment]
@linl33 I would like to work on it, could you please provide more information on where should I document it?

**Comment by linl33** [comment]
Our documentation is at [https://github.com/odk-x/docs](odk-x/docs)

**Comment by IAmJaishree** [comment]
Thanks @linl33, can this issue be assigned to me?  :)

**Comment by linl33** [comment]
Sure, I've assigned this issue to you. Thanks!

**Comment by IAmJaishree** [comment]
@linl33 just to be on the same page I want to confirm the following.

I need to build the documentation project in my local machine and change the source code in order to update the documentation?

**Comment by linl33** [comment]
Yes, you can find more information on the README of https://github.com/odk-x/docs

**Comment by IAmJaishree** [comment]
Thanks, I tried to setup it in windows and I am not able to do it, I am facing some issues there, now I am moving to ubuntu and trying to setup it there.

**Comment by wbrunette** [comment]
The docker setup should be the easiest on windows.

**Comment by IAmJaishree** [comment]
@linl33 @wbrunette I was having issues in setting this up in windows so I did the setup in ubuntu and it is running fine :) Thanks.

I have some queries.

![image](https://user-images.githubusercontent.com/58835654/111301500-4ebae200-8678-11eb-8a25-2364a6bc0bee.png)
This is the QR code scanner whose documentation is not available in Step 2 of  https://docs.odk-x.org/services-managing/#services-managing-server-config this page.

1. Should I add the documentation in Step 2 itself of this page?
2. All the valid QR codes will contain **serverUrl, username and password** or there can be the cases where QR code can contain only some of these values?
3. From where can I get a sample QR code to check its functionality? (this will help me to document it more clearly)

**Comment by wbrunette** [comment]
The application designer has a web tab that will generate the barcode.

https://github.com/odk-x/app-designer/

**Comment by linl33** [comment]
@IAmJaishree Step 2 or 3 on https://docs.odk-x.org/services-managing/#services-managing-server-config are good places to put the documentation.

@elmps2018 Do you have suggestions on where to document this?

**Comment by elmps2018** [comment]
I think step 2 or 3 where you suggest is good for putting all the details. There may be some other places to then mention it and link back to the details. For example: https://docs.odk-x.org/survey-sample-app-install/ does a sample app sync. Putting a tip in there to see https://docs.odk-x.org/services-managing/#services-managing-server-config for how to log in with QR code and likewise here: https://docs.odk-x.org/tables-sample-app-install/

**Comment by linl33** [comment]
@IAmJaishree Could you give us an update on this issue? Let us know if you have any questions.

**Comment by pawanharariya** [comment]
@wbrunette Can I work on this?

**Comment by wbrunette** [comment]
@pawanharariya I have assigned the issue to you.
