### ISSUE TITLE
UI Feature Update in Services : Password Visibility Toggle

### ISSUE THREAD

**Issue by VarunT11** [odk-x/tool-suite-X#200]
**Current Scenario :**
- For Authentication and Updating Password, Users are asked to enter the password in an EditText Field.
- If someone wants to view the entered password, they click on the Checkbox below the EditText and the password gets visible.
![Screenshot_20210313-113448](https://user-images.githubusercontent.com/58032608/111023168-80744480-83fd-11eb-8fc2-dbf8a4bc6a19.jpg)
![Screenshot_20210313-114715](https://user-images.githubusercontent.com/58032608/111023181-9255e780-83fd-11eb-9567-197e27d890c2.jpg)

**Bugs in Current Version**
- If a user is typing their password and wishes to visible it by clicking on the Checkbox or vice-versa, the Cursor is shifted to the start of the EditText.
- Then the Users have to shift the Cursor again to the end and perform the next operation.
![Screenshot_20210313-123658](https://user-images.githubusercontent.com/58032608/111023405-e7dec400-83fe-11eb-88b0-302d64985eec.jpg)
![Screenshot_20210313-123716](https://user-images.githubusercontent.com/58032608/111023408-e9a88780-83fe-11eb-9ff4-643a4e19ecc7.jpg)

**Feature Update :**
- Removing the Checkbox and implementing the EditTextInputField of the Android Support Library instead of the normal EditText.
- This would fix the bug listed above by making the use of Password Visibility Toggle Attribute.
- This would also help in increasing the Efficiency of the Code as the Use and Maintenance of the Checkbox would no longer be required.
- The Application would look like the following after the Feature Update:
![Screenshot_20210313-122355](https://user-images.githubusercontent.com/58032608/111023579-e661cb80-83ff-11eb-81f2-740fdc910648.jpg)
![Screenshot_20210313-122412](https://user-images.githubusercontent.com/58032608/111023580-e82b8f00-83ff-11eb-8af8-948dbebb49a0.jpg)
![Screenshot_20210313-124701](https://user-images.githubusercontent.com/58032608/111023583-e8c42580-83ff-11eb-91d7-04261da6bb39.jpg)
![Screenshot_20210313-124715](https://user-images.githubusercontent.com/58032608/111023586-ea8de900-83ff-11eb-938b-b5fa8e66ae8e.jpg)
 
If this feature update/issue is a valid one, I would like to work on it.

**Comment by wbrunette** [comment]
@VarunT11 this update does change the UI to become closer to current standard interfaces, so go ahead and implement and submit a PR for review.

**Comment by VarunT11** [comment]
@wbrunette I have implemented the changes and submitted the PR for Review at https://github.com/odk-x/services/pull/183
