### ISSUE TITLE
Spinner's selected Item doesn't persist between activity lifecycle changes in services app

### ISSUE THREAD

**Issue by pawanharariya** [odk-x/tool-suite-X#201]
The Sync option spinner's selected item is not saved when user navigates away from the activity. If some other value is selected for Sync Type the spinner's value is set to default when user comes backs to activity and user has to reselect the same option again.

Suppose the option Do Not Sync attachments is selected by the user.

![before](https://user-images.githubusercontent.com/43620548/111073213-ea771180-8503-11eb-9e06-61413d069396.jpg)

After visiting the activity again option is set to default again i.e. Fully sync Attachments

![after](https://user-images.githubusercontent.com/43620548/111073211-e77c2100-8503-11eb-9d3f-fbf1bcb4bd61.jpg)

Problem: If user has some preference of sync option it is not saved and user has to select desired option every time.
Solution: Selected option should be stored as user preference.
Advantage: Better User Experience.

If this is a valid issue, I would like to work upon it.

**Comment by wbrunette** [comment]
@pawanharariya, I agree this would improve the user experience, so go ahead and implement and submit a PR for review.

**Comment by linl33** [comment]
Fixed by odk-x/services#188
