### ISSUE TITLE
Wrong link in Services preferences

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#203]
There is a link in the preferences for Services that points to [http://opendatatkit.org](http://opendatatkit.org). The link should point to [https://docs.odk-x.org](https://docs.odk-x.org) instead.

**Comment by IAmJaishree** [comment]
@linl33 can I work on it?

**Comment by linl33** [comment]
Sure, you may go ahead. Thanks.

**Comment by 96RadhikaJadhav** [comment]
@linl33 Is this issue resolved or still open? If open can I work on it?

**Comment by wbrunette** [comment]
@96RadhikaJadhav the issue is currently assigned to @IAmJaishree to complete.
