### ISSUE TITLE
Update forum name in docs

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#204]
In the footer of the docs it says

> If you still need help, you can ask support questions in the [ODK Forum](https://forum.odk-x.org/)

The link is correct but the text should be `ODK-X Forum` instead.

**Comment by riturajjain2000** [comment]
I'll fix this

**Comment by linl33** [comment]
Hi @riturajjain2000,
Thanks taking on this issue. I've assigned this to you.

**Comment by riturajjain2000** [comment]
Thanks a lot!

**Comment by IAmJaishree** [comment]
I can work on this issue.

**Comment by starboi02** [comment]
Can I work on this?

**Comment by wbrunette** [comment]
@IAmJaishree 
Thanks taking on this issue. I've assigned this to you.
