### ISSUE TITLE
Docs anchor links don't work on Chrome

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#205]
The anchor links, for example https://docs.odk-x.org/#key-features, don't work on Chrome. Firefox is unaffected.
It works when you're navigating to an anchor on the same page, but not when using the full URL.

Removing or blocking the Google translate script appears to fix the issue.

**Comment by starboi02** [comment]
Can I work on it?

**Comment by wbrunette** [comment]
@linl33 I am not sure this is an easy win/ good first issue since it's an open problem. Thoughts?

**Comment by linl33** [comment]
@wbrunette I agree. @starboi02 please pick a different issue.
