### ISSUE TITLE
UI Feature Request : Add toggle button to "Show Splash Screen" and realign "Selected Image"

### ISSUE THREAD

**Issue by riturajjain2000** [odk-x/tool-suite-X#206]
### Current Problem
Currently in the devices, the `Show Splash Screen` option under **Device Settings** is having a checkbox and the `Selected Splash Image ` is a little off to the right from the rest of the options, which I think was done with the intention of showing it as Child of the `Show Splash Screen option`, but is not adding up with the overall UI.

### Screenshot
![Screenshot_1615909055](https://user-images.githubusercontent.com/48384309/111338126-b1be7000-869c-11eb-97c3-dc0b7deaaea7.png)

### Suggested Feature Update
Replacing the checkbox with the toggle button in the `Show Splash Screen` option and aligning the `Selected Splash Image ` with the other options in that Activity.

If this feature update seems valid then, I would like to work on it.

**Comment by wbrunette** [comment]
In the interest of a timely feedback, the PMC/TSC had an email discussion and decided that there are several other preferences in Services that use checkboxes, so for consistency it might be better to keep all of them the same. Also the indentation is helpful for people to realize that one is a child of the other (related). Therefore, we are closing this for now. 

@riturajjain2000 if you are submitting a proposal for GSoC/Outreachy to improve Services' UI please feel free to include this as if it's consistent with your ideas for a redesign then it will become a relevant change. However, while we still have the old design the PMC felt that everything should be kept consistent for now at least.

**Comment by riturajjain2000** [comment]
Thank you for the feedback, @wbrunette  sir. Will include this in my proposal!
