### ISSUE TITLE
AboutMenuFragment gets loaded to Activity stack multiple times

### ISSUE THREAD

**Issue by riturajjain2000** [odk-x/tool-suite-X#210]
### **Bug description**
In the AboutMenuFragment, the menu item `About` is still visible, and if we click on it, the same AboutMenuFragment gets loaded again and again on the Stack, and the back button has to be pressed multiple times in order to exit the fragment.

### **Video**

https://user-images.githubusercontent.com/48384309/111759040-2ffc5b80-88c3-11eb-8826-47b66176bd90.mp4

### **Expected behavior**
The `About` item should be removed from the menu while the user is in AboutMenuFragment.

**Comment by linl33** [comment]
Hi @riturajjain2000,

Thanks for reporting the issue. I agree that the about page should not be loaded multiple times. Would you like to work on this issue?

**Comment by riturajjain2000** [comment]
> Hi @riturajjain2000,
> 
> Thanks for reporting the issue. I agree that the about page should not be loaded multiple times. Would you like to work on this issue?

yes , I am working on it rn

**Comment by linl33** [comment]
@riturajjain2000 I've assigned this issue to you.

**Comment by riturajjain2000** [comment]
Thanks!
