### ISSUE TITLE
Update ODK-X Services description

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#211]
The description on Services' homescreen still refers to ODK-X as ODK 2.0. It should be updated.
https://github.com/odk-x/services/blob/87d47733acad746981be8920782c9789c9a29683/services_app/src/main/res/values/strings.xml#L5

**Comment by starboi02** [comment]
Can I work on it?

**Comment by ADISKING1** [comment]
Can I work on this bug?

**Comment by wbrunette** [comment]
@starboi02 since you have two open issues already assigned to you, I am going to assign this issue to @ADISKING1 so everyone has something to work on.

**Comment by starboi02** [comment]
Ok @wbrunette I understand that.
