### ISSUE TITLE
Bug in settings username

### ISSUE THREAD

**Issue by pawanharariya** [odk-x/tool-suite-X#215]
**Steps to produce:**
1. Go to server settings under settings
2. Enter a multi-line username
3. Press back to move back from activity click log-out
4. Open server settings again under settings

The username gets changed copying itself multiple times.

**Screenshots**
![1](https://user-images.githubusercontent.com/43620548/111899025-c52c5b00-8a4f-11eb-9ecf-ab0495bd1e7c.jpg)
![2](https://user-images.githubusercontent.com/43620548/111899028-c9f10f00-8a4f-11eb-9d6c-dd658da33225.jpg)

**NOTE**
This happens only for multi-line username

I don't know what's causing this bug. But I guess there should be some conditions on username field like no. of lines and length.

P.S. Since this isn't a valid username, which app is used for getting a valid username and password? Maybe the username is being checked there but still the user shouldn't be allowed to enter some random username here.

**Comment by wbrunette** [comment]
@pawanharariya this does seem like a bug. I have assigned it to you to fix. If you don't want to to fix it let me know and I will un-assign you.

**Comment by pawanharariya** [comment]
@wbrunette  I am not actually sure what's causing this bug. Can you provide more information on how the  new username and passwords are generated so that constraint can be added there for multi-line usernames? Here in services settings I can then add the same constraints on username field.

**Comment by pawanharariya** [comment]
I studied the code for a while and found out that this particular section of code is causing the problem.
https://github.com/odk-x/services/blob/c10f7182771aa98482496048f592d95b24a99f13/services_app/src/main/java/org/opendatakit/services/preferences/fragments/ServerSettingsFragment.java#L283-L287

It is actually meant to remove whitespaces but it is also appending the original string after each new line character.
One easy solution could be to prevent the username field from taking multi-line strings because I think there shouldn't be any reason the user to be allowed to use multi-line usernames.
@wbrunette What do you think how to address this issue?
