### ISSUE TITLE
Bug in admin access in settings of services application 

### ISSUE THREAD

**Issue by Shubhamr837** [odk-x/tool-suite-X#216]
The services application has an option of admin access in settings. After entering the password and getting admin access to settings , if the Android device is rotated 
It gets back to normal settings mode.

Steps to reproduce:
1 ) Enable rotation in your Android device .
2 ) open the services application .
3 ) click on the settings option from the menu in top right.
4 ) Click on "admin access to settings" option .
5 ) Enter the password 
6 ) You would now see the additional settings which are available only to the admin. Rotate your device and you will loose the admin access .

Screen recording of the bug :
 https://user-images.githubusercontent.com/45128519/111951698-06814100-8b0a-11eb-8dfd-1b346f25c306.mp4

**Comment by wbrunette** [comment]
@Shubhamr837 you are correct. This is a bug. Did you want to work on this or are you simply reporting it?

**Comment by Shubhamr837** [comment]
@wbrunette Thanks for the reply .
 I would like to work on this issue.

**Comment by wbrunette** [comment]
@Shubhamr837 I have assigned the issue to you.
