### ISSUE TITLE
Provide documentation for Suitcase Upload

### ISSUE THREAD

**Issue by jbeorse** [odk-x/tool-suite-X#53]
#### Software and hardware versions 
ODK Suitcase 2.0.0

#### Problem description
Suitcase documentation doesn't cover uploading and resetting the app server: http://opendatakit-dev.cs.washington.edu/2_0_tools/release/214/suitcase

Furthermore the CLI help descriptions are quite brief and sometimes confusing. These should be updated and the documentation linked above should be updated to be more thorough and clear.

Also, I think the dataVersion CLI option should change to something like API version, or otherwise make it clear that this has nothing to do with the user's data.

**Comment by elmps2018** [comment]
This came up again: https://forum.odk-x.org/t/bulk-deleting-of-data/692

**Comment by ADISKING1** [comment]
Hey @elmps2018,
I'd like to work on it.

**Comment by elmps2018** [comment]
@ADISKING1 just assigned it to you! Let me know any questions I can help with.

**Comment by ADISKING1** [comment]
Thanks! I'll let you know if I'm stuck.

**Comment by ADISKING1** [comment]
I have a question regarding the Upload option in Suitcase GUI.
How do we prepare a folder for Upload and what changes it makes to the server after we upload it?
Thank you.

**Comment by elmps2018** [comment]
@ADISKING1 The work done on https://github.com/odk-x/docs/pull/60 with the CLI shows some of the upload options. And this discussion on the Forum: https://forum.odk-x.org/t/using-suitcase-to-add-and-update-observations/301/6
describes some of the workflow. The basic idea is that you can update the data in tables on your server.

**Comment by ADISKING1** [comment]
I have created a CSV and successfully used it to update, delete and add new entries via CLI but failed to do so using the GUI Upload option.
The Upload option in the GUI requires us to select a folder that contains target & assets folder. How do I setup those folders?

**Comment by elmps2018** [comment]
@ADISKING1 If you have the app designer set up, it should have the assets>csv folder where you could store uploads, is that what you mean? That's typically where one stores csvs that need to be imported to the tab/uploaded to the server. Or if there's something else if you can grab a screenshot of what you mean that would help!

**Comment by wbrunette** [comment]
@ADISKING1 there is a specific file structure that ODK-X uses. What @elmps2018 is referring to is inside config lives the assests folder. You upload the files in the correct file structure because that is where the ODK-X frameworks look for files. Here is a description of the file structure: https://docs.odk-x.org/config-file-structure/

NOTE: The files in the Application Designer zip follow the structure.

**Comment by ADISKING1** [comment]
Thank you @wbrunette @elmps2018 for the clarification.

There is one more thing that's not clear to me. Can the GUI be used to **UPDATE** data?
The existing docs say that we can...
![image](https://user-images.githubusercontent.com/35284932/112379785-95f74180-8d0e-11eb-881d-9f26a6b36e6a.png)

but here it is mentioned that it's possible only via the CLI
![image](https://user-images.githubusercontent.com/35284932/112379333-09e51a00-8d0e-11eb-930c-f200c968ccdd.png)

**Comment by elmps2018** [comment]
@ADISKING1 The Forum comment was from 2018 so I think the graphical interface can now upload as well (you should see that button now) but it needs to be documented more clearly.

**Comment by ADISKING1** [comment]
![image](https://user-images.githubusercontent.com/35284932/112383531-394a5580-8d13-11eb-9f2f-4674f0442c1c.png)
I just checked a release older than that comment, but it still had the upload option.
There a possibility that GUI only supports UPLOAD and not UPDATE.

**Comment by wbrunette** [comment]
@ADISKING1 not sure, you can check the code and see what option is used. Code available here https://github.com/odk-x/suitcase

**Comment by ADISKING1** [comment]
Just checked the code and found that GUI has a method call for [UploadTask.java](https://github.com/odk-x/suitcase/blob/8e6fdc9c5a15a4dd7edcf498a547091b709c796c/src/main/java/org/opendatakit/suitcase/ui/PushPanel.java#L97) but no method calls for [UpdateTask.java](https://github.com/odk-x/suitcase/blob/master/src/main/java/org/opendatakit/suitcase/net/UpdateTask.java) which is responsible for updating.
I believe that there is no option to update via GUI yet and I will write the docs accordingly.

Thank you @wbrunette, @elmps2018 for taking the time to address my doubts.
