### ISSUE TITLE
refactor: Remove redundant View castings in Android projects

### ISSUE THREAD

**Issue by dr0pdb** [odk-x/tool-suite-X#65]
#### Software and hardware versions 
Latest code from development branch.

#### Problem description
Currently there are a lot of instances of redundant View castings in the project. 
For eg. 
``` Java
infoPane = (LinearLayout) view.findViewById(R.id.sync_info_pane);
```
can be replaced by 
```Java
infoPane = view.findViewById(R.id.sync_info_pane);
```
They were required before but aren't required now and Android studio suggests removing them.

#### Steps to reproduce the problem
NA

#### Expected behavior
They should be removed.

#### Other information 
NA

@jbeorse Views ? 
Quick win for first timers may be :smile:

**Comment by VarunT11** [comment]
@linl33 @wbrunette If this issue is still open, I would like to work on this.

**Comment by wbrunette** [comment]
@VarunT11 the issue is still open. I will assign it to you.

**Comment by VarunT11** [comment]
@wbrunette I have removed the Redundant View Castings from _**Android Library**_ in https://github.com/odk-x/androidlibrary/pull/191.
Apart from this, I saw some Redundant Castings in _**Services**_ also which were being suggested to be removed by Android Studio. So shall I remove those Redundant Castings also?

**Comment by linl33** [comment]
@VarunT11 Yes, please remove the ones in Services as well. Thank you.

**Comment by wbrunette** [comment]
@VarunT11 can you check out androidcommon, survey, and tables? Then we can close this issue. Good work!

**Comment by VarunT11** [comment]
@wbrunette Yes Sure! I will check these as well.

**Comment by VarunT11** [comment]
@wbrunette @linl33 While I was going through the code-base of Android Library, there were several instances of suggestion by Android Studio to replace some **Anonymous Methods** with **Lambda Expressions**.
For example, consider the following code snippet -
```java
new DialogInterface.OnClickListener() {
              @Override
              public void onClick(DialogInterface dialog, int which) {

              //Some Code

              }
}
```
The above method was being suggested to be replaced with the following - 
```java
(dialog, which) -> {

              //Some Code

            }
```
This replacement would make some imports unusable and hence we can remove them too.
So shall I replace these **Anonymous Methods** with the **Lambda Expressions**?

**Comment by wbrunette** [comment]
Since the issue is specifically for redundant casts, let's stick to that. Also ODK-X still supports Android devices that run Android 7 that don't support Lamdas. I hope the Android compile system would handle it correctly but not worth creating weird bugs we would have to track down later.

**Comment by VarunT11** [comment]
- **Survey**: Removed the Redundant Castings in https://github.com/odk-x/survey/pull/146.
- **Tables**: Removed the Redundant Castings in https://github.com/odk-x/tables/pull/175.
- **Android Common**: No Redundant Castings Found.

**PS**: @wbrunette @linl33 I have made the PRs. Please review them!
