### ISSUE TITLE
Replace hardcoded column name strings

### ISSUE THREAD

**Issue by wbrunette** [odk-x/tool-suite-X#79]
#### Problem description

The class org.opendatakit.utilities.NameUtils in AndroidLibrary uses hardcoded strings instead of the constant values of the column names. If a column name changes this will cause inconsistencies.

**Comment by VarunT11** [comment]
@wbrunette Can I work on this issue?

**Comment by wbrunette** [comment]
@VarunT11 I have assigned the issue to you.

**Comment by wbrunette** [comment]
@VarunT11 Could you give us an update on this issue? Let us know if you have any questions.

**Comment by VarunT11** [comment]
@wbrunette I have currently identified around 9 files in **Android Library** and around 4 files in **Android Common** which contains Strings that are hardcoded. Many of them are used in Hash Maps. I am currently working to find the usage of these Strings and methods to replace them.

**Comment by wbrunette** [comment]
@VarunT11 there should probably be a class that defines either string consts (most likely) or enums.

**Comment by Lamouresparus** [comment]
Hi @wbrunette I am Love Otudor, an Outreachy applicant. I would like to work on this issue.

**Comment by wbrunette** [comment]
@Lamouresparus I have assigned the issue to you. 
Here is a comment I left in the pull request that fixed some of the hardcoded strings"
"There are still some hardcoded strings in androidlibrary_lib/src/main/java/org/opendatakit/utilities/NameUtil.java:69:

We are simply looking where people put strings in the code they should be changed to be a constant string defined in our constant files.

**Comment by Lamouresparus** [comment]
Hi @wbrunette. I have created a PR for this [here](https://github.com/odk-x/androidlibrary/pull/209).
Thank you 😊
