### ISSUE TITLE
Have a contributor's guide

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#86]

**Comment by maprehensive** [comment]
Actions (from TSC meeting 21 May)
> Redraft Android Tools Setup Instructions - leads to next steps
> - Create a development tools setup wiki page
> - Create a central landing page on docs page for setting up android tools

**Comment by maprehensive** [comment]
Updated links in ODK-X repos, edited content and added paragraph for contributors to README docs. 

Some repos still need setup, prerequisites and other instructions updated and improved.
